services:
  - type: web
    name: dsce-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: MAIN_DIR
        value: backend
      - key: BREVO_API_KEY
        sync: false
